# Generated by Django 2.2.5 on 2021-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ID', models.IntegerField()),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('registration_deadline', models.DateField()),
                ('poster_link', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('email_ID', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particpant_ID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email_ID', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=50)),
                ('registration_type', models.CharField(max_length=20)),
                ('number_of_participants', models.IntegerField(null=True)),
            ],
        ),
    ]
