# Generated by Django 2.2.5 on 2021-01-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('from_date', models.CharField(max_length=50)),
                ('from_time', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=50)),
                ('to_time', models.CharField(max_length=10)),
                ('poster_link', models.TextField()),
                ('host_id', models.TextField()),
            ],
        ),
    ]
