# Generated by Django 2.2.5 on 2021-01-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='particpant_ID',
            new_name='participant_ID',
        ),
    ]
