# Generated by Django 2.2.5 on 2021-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210131_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='number_of_participants',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
